---
--- 统计模块
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/3 15:10
---

-- 模块定义
local _M = {}

-- 定义计数变量
_M.number = 0

-- 模块方法：浏览统计
function _M.count()
    _M.number = _M.number + 1
    ngx.say("c: ", _M.number);
end

-- 模块输出
return _M