---
--- GET 获取，获取 URI 参数
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/5 10:30
---

local uri_args = ngx.req.get_uri_args();

for k, v in pairs(uri_args) do
    if type(v) == "table" then
        ngx.say(k, ":", table.concat(v,","), "<br/>")
    else
        ngx.say(k, ":", v, "<br/>")
    end
end