---
--- 请求对象
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/5 10:01
---
local headers = ngx.req.get_headers()

for k, v in pairs(headers) do
    if type(v) ~= "table" then
        ngx.say(k, ":", v, "<br/>")
    else
        -- table.concat(table, sep,  start, end)  数组转字符串
        -- table: table 数据
        -- sep: 分割符
        -- start: 起始位置
        -- end: 结束位置
        ngx.say(k, ":", table.concat(v,","), "<br/>")
    end
end