---
--- Nginx 变量
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/5 9:49
---

-- Nginx 变量
local var = ngx.var

-- 读取设置的变量
local a = var.a

-- 输出变量
ngx.say(a)