---
--- POST请求，获取POST参数
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/5 10:40
---
ngx.req.read_body()
local post_data = ngx.req.get_post_args()

for k, v in pairs(post_data) do
    if type(v) == "table" then
        ngx.say(k, ":", table.concat(v,","), "<br/>")
    else
        ngx.say(k, ":", v, "<br/>")
    end
end